// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjzttgalsohdjklhnsmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqenR0Z2Fsc29oZGprbGhuc21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTg0NzcsImV4cCI6MjA1ODczNDQ3N30.4dZWaYEA_6hoPDO9GZYNEWhZhdg6NmrgLe04NTIEMis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);